import type { Holding } from "@/lib/types";

// Generates a Form N-PORT Part C (schedule of portfolio investments) XML fragment in the
// shape EDGAR expects. This is a faithful subset — enough to be recognizable and
// schema-plausible as an <invstOrSec> block — not the full 200-field submission.

function esc(v: string | number | null): string {
  if (v === null || v === undefined) return "";
  return String(v)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function money(n: number): string {
  return Number.isFinite(n) ? n.toFixed(2) : "0.00";
}

export interface FilingMeta {
  fundName: string;
  ticker: string;
  seriesId: string; // EDGAR series id, e.g. S000012345
  lei: string;
  repPdDate: string; // reporting period end, YYYY-MM-DD
}

function invstOrSec(h: Holding): string {
  const idBlock = [
    h.lei ? `        <lei>${esc(h.lei)}</lei>` : "",
    `      <identifiers>`,
    h.cusip ? `        <cusip value="${esc(h.cusip)}"/>` : `        <cusip value="N/A"/>`,
    h.isin ? `        <isin value="${esc(h.isin)}"/>` : "",
    h.ticker ? `        <ticker value="${esc(h.ticker)}"/>` : "",
    `      </identifiers>`,
  ]
    .filter(Boolean)
    .join("\n");

  return `    <invstOrSec>
      <name>${esc(h.name)}</name>
      <title>${esc(h.title)}</title>
${idBlock}
      <balance>${esc(h.balance)}</balance>
      <units>${esc(h.units)}</units>
      <curCd>USD</curCd>
      <valUSD>${money(h.valueUsd)}</valUSD>
      <pctVal>${money(h.pctOfNetAssets)}</pctVal>
      <payoffProfile>${esc(h.payoffProfile)}</payoffProfile>
      <assetCat>${esc(h.assetCategory)}</assetCat>
      <issuerCat>${esc(h.issuerCategory)}</issuerCat>
      <invCountry>${esc(h.country)}</invCountry>
      <isRestrictedSec>N</isRestrictedSec>
      <fairValLevel>1</fairValLevel>
    </invstOrSec>`;
}

export function generateNportXml(meta: FilingMeta, holdings: Holding[]): string {
  const totalVal = holdings.reduce((s, h) => s + (Number.isFinite(h.valueUsd) ? h.valueUsd : 0), 0);
  const body = holdings.map(invstOrSec).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by N-PORT Filing Studio. Form N-PORT Part C subset. Not an official SEC submission. -->
<edgarSubmission xmlns="http://www.sec.gov/edgar/nport">
  <headerData>
    <submissionType>NPORT-P</submissionType>
    <filer>
      <seriesId>${esc(meta.seriesId)}</seriesId>
      <lei>${esc(meta.lei)}</lei>
    </filer>
  </headerData>
  <formData>
    <genInfo>
      <regName>${esc(meta.fundName)}</regName>
      <seriesName>${esc(meta.fundName)}</seriesName>
      <ticker>${esc(meta.ticker)}</ticker>
      <repPdEnd>${esc(meta.repPdDate)}</repPdEnd>
      <totAssets>${money(totalVal)}</totAssets>
    </genInfo>
    <invstOrSecs>
${body}
    </invstOrSecs>
  </formData>
</edgarSubmission>
`;
}
